let Courses = [
  // pool 1: mandatory classes
  {
    trimester: 1,
    title: "Cognitive Science & Psychology: Mind, Brain and Behaviour",
    code: 30846,
    numCredits: 5,
    pool: 1,
    url: "https://www.upf.edu/web/csim/syllabus#30846",
    isMandatory: true,
  },
  {
    trimester: 1,
    title: "Research Methodologies in Humanities and Science",
    code: 30845,
    numCredits: 5,
    pool: 1,
    url: "https://www.upf.edu/web/csim/syllabus#30845",
    isMandatory: true,
  },
  {
    trimester: 1,
    title: "Interaction Models",
    code: 30847,
    numCredits: 5,
    pool: 1,
    url: "https://www.upf.edu/web/csim/syllabus#30847",
    isMandatory: true,
  },
  {
    trimester: 2,
    title: "Systems Design, Integration and Control",
    code: 30863,
    numCredits: 5,
    pool: 1,
    url: "https://www.upf.edu/web/csim/syllabus#30863",
    isMandatory: true,
  },

  // pool 2: optional pool (minimum 3)
  {
    trimester: 2,
    title: "Adaptive Behaviour",
    code: 30864,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30864",
  },
  {
    trimester: 3,
    title: "Advanced Concepts and Methods in Cognitive Systems",
    code: 30877,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30877",
  },
  {
    trimester: 2,
    title: "Advanced Interface Design",
    code: 30853,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30853",
  },
  {
    trimester: 2,
    title: "Cognitive Systems: theory and models",
    code: 30860,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30860",
  },
  {
    trimester: 3,
    title: "Education, Games and Entertainment",
    code: 30857,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30857",
  },
  {
    trimester: 1,
    title: "Real Time Interaction",
    code: 30876,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30876",
  },
  {
    trimester: 3,
    title: "Sound Communication",
    code: 30852,
    numCredits: 5,
    pool: 2,
    url: "https://www.upf.edu/web/csim/syllabus#30852",
  },

  // pool 3: expansion pool (maximum 1)
  {
    trimester: 1,
    title: "Audio Signal Processing for Music Applications",
    code: 30226,
    numCredits: 5,
    pool: 3,
    url: "https://www.upf.edu/en/web/smc/audio-signal-processing-for-music-applications",
  },
  {
    trimester: 1,
    title: "Autonomous Systems",
    code: 31641,
    numCredits: 5,
    pool: 3,
    url: "https://www.upf.edu/iis/program.html#AS",
  },
  {
    trimester: 1,
    title: "Machine Learning",
    code: 31645,
    numCredits: 5,
    pool: 3,
    url: "https://www.upf.edu/iis/program.html#ML",
  },
  {
    trimester: 1,
    title: "Mobile Robotics",
    code: 31643,
    numCredits: 5,
    pool: 3,
    url: "https://www.upf.edu/iis/program.html#MR",
  },
  {
    trimester: 2,
    title: "Natural Language Interaction",
    code: 31642,
    numCredits: 5,
    pool: 3,
    url: "https://www.upf.edu/iis/program.html#NL",
  },
  
];
Courses = _.orderBy(Courses, ['trimester'], ['asc']);
export default Courses;